[package]
name = "kyber-pke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pqc_kyber = { git = "https://github.com/Argyle-Software/kyber.git", branch = "master" }